github:
  is_project_page: false

plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true

theme: jekyll-theme-cayman

title: [Scrum 指南：简体中文版]
description: [让我们一起创建社区版本以共享知识]
show_downloads: false
google_analytics: UA-177167416-1
