github:
  is_project_page: false

plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true

theme: jekyll-theme-cayman

title: [Scrum 指南™：简体中文版]
description: [官方版的 Scrum指南™ 是英文。但是我们可以一起打造我们的社群版本!]
show_downloads: false
google_analytics: UA-177167416-1
